<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Government Sources</title><style>
body{font-family:system-ui,-apple-system,Segoe UI,sans-serif;margin:0;background:#f4f6f8;color:#111827}nav{background:#111827;padding:14px 24px}nav a{color:#fff;text-decoration:none;margin-right:20px}.wrap{max-width:1320px;margin:28px auto;padding:0 18px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:18px;box-shadow:0 2px 8px rgba(0,0,0,.03)}h1{margin-top:0}table{width:100%;border-collapse:collapse}th,td{padding:11px;border-bottom:1px solid #eee;text-align:left;vertical-align:top}button,.btn{display:inline-block;background:#111827;color:#fff;border:0;border-radius:7px;padding:9px 13px;text-decoration:none;cursor:pointer}.crawl{background:#166534}.stop{background:#b91c1c}.muted{color:#6b7280}.flash{background:#ecfdf5;border:1px solid #a7f3d0;padding:12px;border-radius:8px;margin-bottom:16px}.error{background:#fef2f2;border:1px solid #fecaca;padding:12px;border-radius:8px;margin-bottom:16px}.top-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.top-actions form{margin:0}.pill{display:inline-flex;align-items:center;gap:7px;padding:5px 9px;border-radius:999px;font-size:12px;font-weight:700;background:#f3f4f6;color:#4b5563}.dot{width:8px;height:8px;border-radius:50%;background:#9ca3af}.running{background:#eff6ff;color:#1d4ed8}.running .dot{background:#2563eb;animation:pulse 1s infinite}.completed{background:#ecfdf5;color:#166534}.completed .dot{background:#16a34a}.failed{background:#fef2f2;color:#991b1b}.failed .dot{background:#dc2626}.stopped{background:#fff7ed;color:#9a3412}.stopped .dot{background:#f97316}.pending{background:#f3f4f6;color:#6b7280}.progress-wrap{margin-top:14px}.bar{height:10px;background:#e5e7eb;border-radius:999px;overflow:hidden}.bar>div{height:100%;background:#2563eb;width:0%;transition:width .3s}.summary{font-size:13px;margin-top:7px;color:#4b5563}@keyframes pulse{50%{opacity:.25}}@media(max-width:800px){table{display:block;overflow:auto}}
</style></head><body><nav><a href="/">Dashboard</a><a href="/sources">Sources</a><a href="/reviews">Found Jobs</a></nav><main class="wrap"><?php if(session('status')): ?><div class="flash"><?= e(session('status')) ?></div><?php endif; ?><?php if(session('error')): ?><div class="error"><?= e(session('error')) ?></div><?php endif; ?><div class="card"><h1>Government Sources</h1><div class="top-actions"><form method="post" action="/sources/crawl-all"><?= csrf_field() ?><button class="crawl" type="submit">Start / Resume Crawler</button></form><form method="post" action="/sources/stop-all"><?= csrf_field() ?><button class="stop" type="submit">Stop Crawler</button></form><a class="btn" href="/sources/create">Add Government Source</a><span id="overall-pill" class="pill pending"><span class="dot"></span><span id="overall-text">Idle</span></span></div><div class="progress-wrap"><div class="bar"><div id="progress-bar"></div></div><div class="summary" id="progress-summary">Waiting for crawler status…</div></div></div><div class="card"><table><thead><tr><th>Source</th><th>Mode</th><th>Source Status</th><th>Crawler</th><th>Last crawl</th><th>Action</th></tr></thead><tbody><?php foreach($sources as $s): ?><tr data-source-row="<?= (int)$s->id ?>"><td><strong><?= e($s->name) ?></strong><br><span class="muted"><?= e($s->organization) ?></span><br><small><?= e($s->recruitment_url) ?></small></td><td><?= e($s->crawler_mode->value) ?></td><td><?= e($s->status->value) ?></td><td><span class="pill pending crawl-state" data-source-id="<?= (int)$s->id ?>"><span class="dot"></span><span>Pending</span></span><div class="muted crawl-error" data-error-id="<?= (int)$s->id ?>" style="font-size:11px;margin-top:4px"></div></td><td><?= e($s->last_crawled_at ?: 'Never') ?></td><td><form style="display:inline" method="post" action="/sources/<?= (int)$s->id ?>/toggle"><?= csrf_field() ?><button type="submit"><?= $s->status->value==='active'?'Pause':'Activate' ?></button></form></td></tr><?php endforeach; ?></tbody></table><div style="margin-top:14px"><?= $sources->links() ?></div></div></main><script>
const labels={idle:'Idle',running:'Running',completed:'Completed',failed:'Failed',stopped:'Stopped',pending:'Pending'};
function setPill(el,status,text){ if(!el)return; el.className='pill '+(status||'pending')+(el.classList.contains('crawl-state')?' crawl-state':''); const span=el.querySelector('span:last-child'); if(span) span.textContent=text||labels[status]||status; }
async function refresh(){
 try{
  const r=await fetch('/sources/crawl-status',{cache:'no-store'}); const d=await r.json();
  const overall=document.getElementById('overall-pill'); setPill(overall,d.status||'idle',labels[d.status]||d.status||'Idle');
  const processed=Number(d.processed||0), total=Number(d.total||0), pct=total?Math.round(processed*100/total):0;
  document.getElementById('progress-bar').style.width=pct+'%';
  document.getElementById('progress-summary').textContent=(d.status||'idle')+' · '+processed+'/'+total+' sites processed · '+Number(d.succeeded||0)+' completed · '+Number(d.failed||0)+' failed';
  document.querySelectorAll('.crawl-state').forEach(el=>{ const id=String(el.dataset.sourceId), s=(d.sources||{})[id]||{status:'pending'}; setPill(el,s.status||'pending',labels[s.status]||s.status||'Pending'); const er=document.querySelector('[data-error-id="'+id+'"]'); if(er) er.textContent=s.error||''; });
 }catch(e){}
}
refresh(); setInterval(refresh,2000);
</script></body></html>