<?php
return [
  [
    'source_key'=>'mib', 'name'=>'MIB Vacancies', 'organization'=>'Ministry of Information & Broadcasting',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'mib.gov.in', 'recruitment_url'=>'https://mib.gov.in/index.php/offerings/vacancies', 'crawler_mode'=>'HTML',
    'source_order'=>1, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'mib','source_order'=>1,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'dot', 'name'=>'DoT Vacancies', 'organization'=>'Department of Telecommunications',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'dot.gov.in', 'recruitment_url'=>'https://www.dot.gov.in/all-vacancies', 'crawler_mode'=>'HTML',
    'source_order'=>2, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'dot','source_order'=>2,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'niti-aayog', 'name'=>'NITI Aayog Vacancy Circulars', 'organization'=>'NITI Aayog',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'niti.gov.in', 'recruitment_url'=>'https://www.niti.gov.in/work-niti/vacancy-circular', 'crawler_mode'=>'HTML',
    'source_order'=>3, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'niti-aayog','source_order'=>3,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'mohfw', 'name'=>'MoHFW Vacancies', 'organization'=>'Ministry of Health & Family Welfare',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'mohfw.gov.in', 'recruitment_url'=>'https://www.mohfw.gov.in/?q=vacancy', 'crawler_mode'=>'HTML',
    'source_order'=>4, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'mohfw','source_order'=>4,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'mha', 'name'=>'MHA Vacancies', 'organization'=>'Ministry of Home Affairs',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'mha.gov.in', 'recruitment_url'=>'https://www.mha.gov.in/en/notifications/vacancies', 'crawler_mode'=>'HTML',
    'source_order'=>5, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'mha','source_order'=>5,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'upsc', 'name'=>'UPSC Recruitment Advertisements', 'organization'=>'Union Public Service Commission',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'upsc.gov.in', 'recruitment_url'=>'https://www.upsc.gov.in/recruitment/recruitment-advertisement', 'crawler_mode'=>'HTML',
    'source_order'=>6, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'upsc','source_order'=>6,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'ssc', 'name'=>'SSC Notice Board', 'organization'=>'Staff Selection Commission',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'ssc.gov.in', 'recruitment_url'=>'https://ssc.gov.in/', 'crawler_mode'=>'AUTO',
    'source_order'=>7, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'ssc','source_order'=>7,'listing_is_recruitment'=>false,'force_browser'=>true,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'drdo', 'name'=>'DRDO Vacancies', 'organization'=>'Defence Research and Development Organisation',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'drdo.gov.in', 'recruitment_url'=>'https://drdo.gov.in/drdo/offerings/vacancies', 'crawler_mode'=>'HTML',
    'source_order'=>8, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'drdo','source_order'=>8,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'rbi', 'name'=>'RBI Current Vacancies', 'organization'=>'Reserve Bank of India',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'rbi.org.in', 'recruitment_url'=>'https://opportunities.rbi.org.in/Scripts/Vacancies.aspx', 'crawler_mode'=>'AUTO',
    'source_order'=>9, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'rbi','source_order'=>9,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'indian-army', 'name'=>'Indian Army Recruitment', 'organization'=>'Indian Army',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'joinindianarmy.nic.in', 'recruitment_url'=>'https://www.joinindianarmy.nic.in/default.aspx', 'crawler_mode'=>'JS',
    'source_order'=>10, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'indian-army','source_order'=>10,'listing_is_recruitment'=>false,'force_browser'=>true,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'indian-navy', 'name'=>'Indian Navy Recruitment', 'organization'=>'Indian Navy',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'joinindiannavy.gov.in', 'recruitment_url'=>'https://www.joinindiannavy.gov.in/', 'crawler_mode'=>'JS',
    'source_order'=>11, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'indian-navy','source_order'=>11,'listing_is_recruitment'=>false,'force_browser'=>true,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'indian-air-force', 'name'=>'Indian Air Force AFCAT', 'organization'=>'Indian Air Force',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'afcat.cdac.in', 'recruitment_url'=>'https://afcat.cdac.in/AFCAT/', 'crawler_mode'=>'JS',
    'source_order'=>12, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'indian-air-force','source_order'=>12,'listing_is_recruitment'=>true,'force_browser'=>true,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'kerala-psc', 'name'=>'Kerala PSC Notifications', 'organization'=>'Kerala Public Service Commission',
    'government_level'=>'State', 'state'=>'Kerala', 'department'=>null,
    'official_domain'=>'keralapsc.gov.in', 'recruitment_url'=>'https://www.keralapsc.gov.in/notifications', 'crawler_mode'=>'HTML',
    'source_order'=>13, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'kerala-psc','source_order'=>13,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'yadgir-recruitment', 'name'=>'Yadgir District Recruitment', 'organization'=>'District Administration Yadgir',
    'government_level'=>'State', 'state'=>'Karnataka', 'department'=>null,
    'official_domain'=>'yadgir.nic.in', 'recruitment_url'=>'https://yadgir.nic.in/en/notice_category/recruitment/', 'crawler_mode'=>'HTML',
    'source_order'=>14, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'yadgir-recruitment','source_order'=>14,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'aiims-jodhpur', 'name'=>'AIIMS Jodhpur Recruitment', 'organization'=>'AIIMS Jodhpur',
    'government_level'=>'Central', 'state'=>'Rajasthan', 'department'=>null,
    'official_domain'=>'aiimsjodhpur.edu.in', 'recruitment_url'=>'https://www.aiimsjodhpur.edu.in/index.php', 'crawler_mode'=>'AUTO',
    'source_order'=>15, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'aiims-jodhpur','source_order'=>15,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'aiims-nagpur', 'name'=>'AIIMS Nagpur Recruitment', 'organization'=>'AIIMS Nagpur',
    'government_level'=>'Central', 'state'=>'Maharashtra', 'department'=>null,
    'official_domain'=>'aiimsnagpur.edu.in', 'recruitment_url'=>'https://aiimsnagpur.edu.in/recruitment', 'crawler_mode'=>'HTML',
    'source_order'=>20, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'aiims-nagpur','source_order'=>20,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'assam-psc', 'name'=>'Assam PSC Recruitment Portal', 'organization'=>'Assam Public Service Commission',
    'government_level'=>'State', 'state'=>'Assam', 'department'=>null,
    'official_domain'=>'apscrecruitment.in', 'recruitment_url'=>'https://apscrecruitment.in/', 'crawler_mode'=>'JS',
    'source_order'=>21, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'assam-psc','source_order'=>21,'listing_is_recruitment'=>true,'force_browser'=>true,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'bpssc', 'name'=>'Bihar Police Subordinate Services Commission', 'organization'=>'Bihar Police Subordinate Services Commission',
    'government_level'=>'State', 'state'=>'Bihar', 'department'=>null,
    'official_domain'=>'bpssc.bihar.gov.in', 'recruitment_url'=>'https://bpssc.bihar.gov.in/', 'crawler_mode'=>'AUTO',
    'source_order'=>22, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'bpssc','source_order'=>22,'listing_is_recruitment'=>false,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'btsc', 'name'=>'BTSC Recruitment', 'organization'=>'Bihar Technical Service Commission',
    'government_level'=>'State', 'state'=>'Bihar', 'department'=>null,
    'official_domain'=>'btsc.bihar.gov.in', 'recruitment_url'=>'https://btsc.bihar.gov.in/recruitment', 'crawler_mode'=>'HTML',
    'source_order'=>23, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'btsc','source_order'=>23,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'kea', 'name'=>'Karnataka Examination Authority Recruitment', 'organization'=>'Karnataka Examination Authority',
    'government_level'=>'State', 'state'=>'Karnataka', 'department'=>null,
    'official_domain'=>'cetonline.karnataka.gov.in', 'recruitment_url'=>'https://cetonline.karnataka.gov.in/kea', 'crawler_mode'=>'JS',
    'source_order'=>24, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'kea','source_order'=>24,'listing_is_recruitment'=>false,'force_browser'=>true,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'cisf', 'name'=>'CISF Recruitment', 'organization'=>'Central Industrial Security Force',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'cisfrectt.cisf.gov.in', 'recruitment_url'=>'https://cisfrectt.cisf.gov.in/', 'crawler_mode'=>'JS',
    'source_order'=>25, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'cisf','source_order'=>25,'listing_is_recruitment'=>true,'force_browser'=>true,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'dpcc', 'name'=>'Delhi Pollution Control Committee Recruitment', 'organization'=>'Delhi Pollution Control Committee',
    'government_level'=>'UT', 'state'=>'Delhi', 'department'=>null,
    'official_domain'=>'dpcc.delhi.gov.in', 'recruitment_url'=>'https://dpcc.delhi.gov.in/', 'crawler_mode'=>'AUTO',
    'source_order'=>26, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'dpcc','source_order'=>26,'listing_is_recruitment'=>false,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'dsssb', 'name'=>'DSSSB Vacancies', 'organization'=>'Delhi Subordinate Services Selection Board',
    'government_level'=>'UT', 'state'=>'Delhi', 'department'=>null,
    'official_domain'=>'dsssb.delhi.gov.in', 'recruitment_url'=>'https://dsssb.delhi.gov.in/vacancies', 'crawler_mode'=>'HTML',
    'source_order'=>27, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'dsssb','source_order'=>27,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iitm-faculty', 'name'=>'IIT Madras Faculty Recruitment', 'organization'=>'Indian Institute of Technology Madras',
    'government_level'=>'Central', 'state'=>'Tamil Nadu', 'department'=>null,
    'official_domain'=>'facapp.iitm.ac.in', 'recruitment_url'=>'https://facapp.iitm.ac.in/index.php', 'crawler_mode'=>'AUTO',
    'source_order'=>28, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iitm-faculty','source_order'=>28,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'hprca', 'name'=>'HPRCA Advertisements', 'organization'=>'Himachal Pradesh Rajya Chayan Aayog',
    'government_level'=>'State', 'state'=>'Himachal Pradesh', 'department'=>null,
    'official_domain'=>'hprca.hp.gov.in', 'recruitment_url'=>'https://hprca.hp.gov.in/', 'crawler_mode'=>'HTML',
    'source_order'=>29, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'hprca','source_order'=>29,'listing_is_recruitment'=>false,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iitgn-staff', 'name'=>'IIT Gandhinagar Staff Recruitment', 'organization'=>'Indian Institute of Technology Gandhinagar',
    'government_level'=>'Central', 'state'=>'Gujarat', 'department'=>null,
    'official_domain'=>'iitgn.ac.in', 'recruitment_url'=>'https://iitgn.ac.in/careers/staff', 'crawler_mode'=>'HTML',
    'source_order'=>30, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iitgn-staff','source_order'=>30,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iitgn-postdoc', 'name'=>'IIT Gandhinagar Postdoctoral Fellowship', 'organization'=>'Indian Institute of Technology Gandhinagar',
    'government_level'=>'Central', 'state'=>'Gujarat', 'department'=>null,
    'official_domain'=>'iitgn.ac.in', 'recruitment_url'=>'https://iitgn.ac.in/academics/pdfellowship', 'crawler_mode'=>'HTML',
    'source_order'=>31, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iitgn-postdoc','source_order'=>31,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'jkssb', 'name'=>'JKSSB Advertisements', 'organization'=>'Jammu and Kashmir Services Selection Board',
    'government_level'=>'UT', 'state'=>'Jammu and Kashmir', 'department'=>null,
    'official_domain'=>'jkssb.nic.in', 'recruitment_url'=>'https://www.jkssb.nic.in/Advertisement.html', 'crawler_mode'=>'HTML',
    'source_order'=>32, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'jkssb','source_order'=>32,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'jssc', 'name'=>'JSSC Recruitment', 'organization'=>'Jharkhand Staff Selection Commission',
    'government_level'=>'State', 'state'=>'Jharkhand', 'department'=>null,
    'official_domain'=>'jssc.jharkhand.gov.in', 'recruitment_url'=>'https://jssc.jharkhand.gov.in/', 'crawler_mode'=>'AUTO',
    'source_order'=>33, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'jssc','source_order'=>33,'listing_is_recruitment'=>false,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'tg-wdcw', 'name'=>'Telangana WDCW Recruitment', 'organization'=>'Women Development and Child Welfare Department Telangana',
    'government_level'=>'State', 'state'=>'Telangana', 'department'=>null,
    'official_domain'=>'mis.tgwdcw.in', 'recruitment_url'=>'https://mis.tgwdcw.in/Recruit_inter.aspx', 'crawler_mode'=>'HTML',
    'source_order'=>34, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'tg-wdcw','source_order'=>34,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'mpphscl', 'name'=>'MPPHSCL Recruitment', 'organization'=>'Madhya Pradesh Public Health Services Corporation Limited',
    'government_level'=>'State', 'state'=>'Madhya Pradesh', 'department'=>null,
    'official_domain'=>'mpphscl.mp.gov.in', 'recruitment_url'=>'https://mpphscl.mp.gov.in/', 'crawler_mode'=>'AUTO',
    'source_order'=>35, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'mpphscl','source_order'=>35,'listing_is_recruitment'=>false,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'mizoram-psc', 'name'=>'Mizoram PSC Advertisements', 'organization'=>'Mizoram Public Service Commission',
    'government_level'=>'State', 'state'=>'Mizoram', 'department'=>null,
    'official_domain'=>'mpsc.mizoram.gov.in', 'recruitment_url'=>'https://mpsc.mizoram.gov.in/', 'crawler_mode'=>'HTML',
    'source_order'=>36, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'mizoram-psc','source_order'=>36,'listing_is_recruitment'=>false,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'mizoram-psc-online', 'name'=>'Mizoram PSC Online Recruitment', 'organization'=>'Mizoram Public Service Commission',
    'government_level'=>'State', 'state'=>'Mizoram', 'department'=>null,
    'official_domain'=>'mpsconline.mizoram.gov.in', 'recruitment_url'=>'https://mpsconline.mizoram.gov.in/', 'crawler_mode'=>'JS',
    'source_order'=>37, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'mizoram-psc-online','source_order'=>37,'listing_is_recruitment'=>true,'force_browser'=>true,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'ncrtc', 'name'=>'NCRTC Careers', 'organization'=>'National Capital Region Transport Corporation',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'ncrtc.in', 'recruitment_url'=>'https://ncrtc.in/career/', 'crawler_mode'=>'HTML',
    'source_order'=>38, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'ncrtc','source_order'=>38,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'nit-calicut', 'name'=>'NIT Calicut Recruitments', 'organization'=>'National Institute of Technology Calicut',
    'government_level'=>'Central', 'state'=>'Kerala', 'department'=>null,
    'official_domain'=>'nitc.ac.in', 'recruitment_url'=>'https://nitc.ac.in/noticeboard/recruitments', 'crawler_mode'=>'HTML',
    'source_order'=>39, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'nit-calicut','source_order'=>39,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'nit-warangal', 'name'=>'NIT Warangal Staff Recruitment', 'organization'=>'National Institute of Technology Warangal',
    'government_level'=>'Central', 'state'=>'Telangana', 'department'=>null,
    'official_domain'=>'nitw.ac.in', 'recruitment_url'=>'https://nitw.ac.in/staffrecruit', 'crawler_mode'=>'HTML',
    'source_order'=>40, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'nit-warangal','source_order'=>40,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'ojas-gujarat', 'name'=>'OJAS Gujarat Current Advertisements', 'organization'=>'Government of Gujarat OJAS',
    'government_level'=>'State', 'state'=>'Gujarat', 'department'=>null,
    'official_domain'=>'ojas.gujarat.gov.in', 'recruitment_url'=>'https://ojas.gujarat.gov.in/', 'crawler_mode'=>'JS',
    'source_order'=>41, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'ojas-gujarat','source_order'=>41,'listing_is_recruitment'=>true,'force_browser'=>true,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'opsc-echayan', 'name'=>'OPSC eChayan', 'organization'=>'Odisha Public Service Commission',
    'government_level'=>'State', 'state'=>'Odisha', 'department'=>null,
    'official_domain'=>'opscechayan.in', 'recruitment_url'=>'https://opscechayan.in/', 'crawler_mode'=>'JS',
    'source_order'=>42, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'opsc-echayan','source_order'=>42,'listing_is_recruitment'=>true,'force_browser'=>true,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'rac-drdo', 'name'=>'RAC DRDO Recruitment', 'organization'=>'Recruitment and Assessment Centre DRDO',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'rac.gov.in', 'recruitment_url'=>'https://rac.gov.in/', 'crawler_mode'=>'AUTO',
    'source_order'=>43, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'rac-drdo','source_order'=>43,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'ramanagara-court', 'name'=>'Ramanagara District Court Recruitment', 'organization'=>'Ramanagara District Court',
    'government_level'=>'State', 'state'=>'Karnataka', 'department'=>null,
    'official_domain'=>'ramanagara.dcourts.gov.in', 'recruitment_url'=>'https://ramanagara.dcourts.gov.in/notice-category/recruitments/', 'crawler_mode'=>'AUTO',
    'source_order'=>44, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'ramanagara-court','source_order'=>44,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'rpsc', 'name'=>'RPSC Recruitments', 'organization'=>'Rajasthan Public Service Commission',
    'government_level'=>'State', 'state'=>'Rajasthan', 'department'=>null,
    'official_domain'=>'rpsc.rajasthan.gov.in', 'recruitment_url'=>'https://rpsc.rajasthan.gov.in/?frmapp=yes', 'crawler_mode'=>'HTML',
    'source_order'=>45, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'rpsc','source_order'=>45,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'scdrc-chandigarh', 'name'=>'SCDRC Chandigarh Recruitment', 'organization'=>'State Consumer Disputes Redressal Commission Chandigarh',
    'government_level'=>'UT', 'state'=>'Chandigarh', 'department'=>null,
    'official_domain'=>'scdrc.chdadmnrectt.in', 'recruitment_url'=>'https://scdrc.chdadmnrectt.in/', 'crawler_mode'=>'AUTO',
    'source_order'=>46, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'scdrc-chandigarh','source_order'=>46,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'up-anganwadi', 'name'=>'UP Anganwadi Recruitment', 'organization'=>'Uttar Pradesh Anganwadi Recruitment',
    'government_level'=>'State', 'state'=>'Uttar Pradesh', 'department'=>null,
    'official_domain'=>'upanganwadibharti.in', 'recruitment_url'=>'https://upanganwadibharti.in/', 'crawler_mode'=>'JS',
    'source_order'=>47, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'up-anganwadi','source_order'=>47,'listing_is_recruitment'=>true,'force_browser'=>true,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'aai', 'name'=>'AAI Recruitment Dashboard', 'organization'=>'Airports Authority of India',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'aai.aero', 'recruitment_url'=>'https://www.aai.aero/en/careers/recruitment', 'crawler_mode'=>'HTML',
    'source_order'=>48, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'aai','source_order'=>48,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'aiims-delhi', 'name'=>'AIIMS New Delhi Recruitment', 'organization'=>'All India Institute of Medical Sciences New Delhi',
    'government_level'=>'Central', 'state'=>'Delhi', 'department'=>null,
    'official_domain'=>'aiims.edu', 'recruitment_url'=>'https://www.aiims.edu/index.php/en/notices/recruitment/aiims-recruitment', 'crawler_mode'=>'HTML',
    'source_order'=>49, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'aiims-delhi','source_order'=>49,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'allahabad-high-court', 'name'=>'Allahabad High Court Recruitments', 'organization'=>'Allahabad High Court',
    'government_level'=>'State', 'state'=>'Uttar Pradesh', 'department'=>null,
    'official_domain'=>'allahabadhighcourt.in', 'recruitment_url'=>'https://www.allahabadhighcourt.in/calendar/itemWiseList.jsp?group=7&page=1', 'crawler_mode'=>'HTML',
    'source_order'=>50, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'allahabad-high-court','source_order'=>50,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'ceeri', 'name'=>'CSIR-CEERI Recruitment Portal', 'organization'=>'CSIR Central Electronics Engineering Research Institute',
    'government_level'=>'Central', 'state'=>'Rajasthan', 'department'=>null,
    'official_domain'=>'exam.ceeri.res.in', 'recruitment_url'=>'https://exam.ceeri.res.in/', 'crawler_mode'=>'HTML',
    'source_order'=>51, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'ceeri','source_order'=>51,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'civil-aviation', 'name'=>'Ministry of Civil Aviation Recruitment', 'organization'=>'Ministry of Civil Aviation',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'civilaviation.gov.in', 'recruitment_url'=>'https://www.civilaviation.gov.in/index.php/tenders-notices/recruitment/recruitment-archive', 'crawler_mode'=>'HTML',
    'source_order'=>52, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'civil-aviation','source_order'=>52,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'gujarat-university', 'name'=>'Gujarat University Careers', 'organization'=>'Gujarat University',
    'government_level'=>'State', 'state'=>'Gujarat', 'department'=>null,
    'official_domain'=>'gujaratuniversity.ac.in', 'recruitment_url'=>'https://www.gujaratuniversity.ac.in/Career', 'crawler_mode'=>'HTML',
    'source_order'=>53, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'gujarat-university','source_order'=>53,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iari', 'name'=>'ICAR-IARI Contractual Jobs', 'organization'=>'ICAR Indian Agricultural Research Institute',
    'government_level'=>'Central', 'state'=>'Delhi', 'department'=>null,
    'official_domain'=>'iari.res.in', 'recruitment_url'=>'https://www.iari.res.in/bms/announcements/jobs.php', 'crawler_mode'=>'HTML',
    'source_order'=>54, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iari','source_order'=>54,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'icsi', 'name'=>'ICSI Recruitment', 'organization'=>'Institute of Company Secretaries of India',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'stimulate.icsi.edu', 'recruitment_url'=>'https://stimulate.icsi.edu/RECRUITMENT/indexhome/indexhome', 'crawler_mode'=>'HTML',
    'source_order'=>55, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'icsi','source_order'=>55,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iiitm-gwalior', 'name'=>'IIITM Gwalior Recruitments', 'organization'=>'ABV Indian Institute of Information Technology and Management Gwalior',
    'government_level'=>'Central', 'state'=>'Madhya Pradesh', 'department'=>null,
    'official_domain'=>'iiitm.ac.in', 'recruitment_url'=>'https://www.iiitm.ac.in/recruitments', 'crawler_mode'=>'HTML',
    'source_order'=>56, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iiitm-gwalior','source_order'=>56,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iim-jammu', 'name'=>'IIM Jammu Jobs', 'organization'=>'Indian Institute of Management Jammu',
    'government_level'=>'Central', 'state'=>'Jammu and Kashmir', 'department'=>null,
    'official_domain'=>'iimj.ac.in', 'recruitment_url'=>'https://www.iimj.ac.in/career.php', 'crawler_mode'=>'HTML',
    'source_order'=>57, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iim-jammu','source_order'=>57,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iit-bhu', 'name'=>'IIT BHU Recruitment', 'organization'=>'Indian Institute of Technology BHU',
    'government_level'=>'Central', 'state'=>'Uttar Pradesh', 'department'=>null,
    'official_domain'=>'iitbhu.ac.in', 'recruitment_url'=>'https://www.iitbhu.ac.in/', 'crawler_mode'=>'AUTO',
    'source_order'=>58, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iit-bhu','source_order'=>58,'listing_is_recruitment'=>false,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iit-dharwad', 'name'=>'IIT Dharwad Staff Recruitment', 'organization'=>'Indian Institute of Technology Dharwad',
    'government_level'=>'Central', 'state'=>'Karnataka', 'department'=>null,
    'official_domain'=>'iitdh.ac.in', 'recruitment_url'=>'https://www.iitdh.ac.in/staff-recruitment', 'crawler_mode'=>'HTML',
    'source_order'=>59, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iit-dharwad','source_order'=>59,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iit-hyderabad', 'name'=>'IIT Hyderabad Careers', 'organization'=>'Indian Institute of Technology Hyderabad',
    'government_level'=>'Central', 'state'=>'Telangana', 'department'=>null,
    'official_domain'=>'iith.ac.in', 'recruitment_url'=>'https://www.iith.ac.in/careers/', 'crawler_mode'=>'HTML',
    'source_order'=>60, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iit-hyderabad','source_order'=>60,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iit-ism-faculty', 'name'=>'IIT ISM Faculty Positions', 'organization'=>'Indian Institute of Technology ISM Dhanbad',
    'government_level'=>'Central', 'state'=>'Jharkhand', 'department'=>null,
    'official_domain'=>'iitism.ac.in', 'recruitment_url'=>'https://www.iitism.ac.in/faculty-positions', 'crawler_mode'=>'HTML',
    'source_order'=>61, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iit-ism-faculty','source_order'=>61,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iit-ism-nonfaculty', 'name'=>'IIT ISM Non-Faculty Careers', 'organization'=>'Indian Institute of Technology ISM Dhanbad',
    'government_level'=>'Central', 'state'=>'Jharkhand', 'department'=>null,
    'official_domain'=>'iitism.ac.in', 'recruitment_url'=>'https://www.iitism.ac.in/career-non-faculty', 'crawler_mode'=>'HTML',
    'source_order'=>62, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iit-ism-nonfaculty','source_order'=>62,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iit-mandi-nonteaching', 'name'=>'IIT Mandi Non-Teaching Recruitment', 'organization'=>'Indian Institute of Technology Mandi',
    'government_level'=>'Central', 'state'=>'Himachal Pradesh', 'department'=>null,
    'official_domain'=>'iitmandi.ac.in', 'recruitment_url'=>'https://www.iitmandi.ac.in/recruitments/non-teaching', 'crawler_mode'=>'HTML',
    'source_order'=>63, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iit-mandi-nonteaching','source_order'=>63,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'iit-roorkee-careers', 'name'=>'IIT Roorkee Careers', 'organization'=>'Indian Institute of Technology Roorkee',
    'government_level'=>'Central', 'state'=>'Uttarakhand', 'department'=>null,
    'official_domain'=>'iitr.ac.in', 'recruitment_url'=>'https://iitr.ac.in/Careers/', 'crawler_mode'=>'HTML',
    'source_order'=>64, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'iit-roorkee-careers','source_order'=>64,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'jncasr', 'name'=>'JNCASR Opportunities', 'organization'=>'Jawaharlal Nehru Centre for Advanced Scientific Research',
    'government_level'=>'Central', 'state'=>'Karnataka', 'department'=>null,
    'official_domain'=>'jncasr.ac.in', 'recruitment_url'=>'https://www.jncasr.ac.in/', 'crawler_mode'=>'AUTO',
    'source_order'=>65, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'jncasr','source_order'=>65,'listing_is_recruitment'=>false,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'mpez', 'name'=>'MPEZ Career Opportunities', 'organization'=>'Madhya Pradesh Poorv Kshetra Vidyut Vitaran Company',
    'government_level'=>'State', 'state'=>'Madhya Pradesh', 'department'=>null,
    'official_domain'=>'mpez.co.in', 'recruitment_url'=>'https://www.mpez.co.in/career', 'crawler_mode'=>'HTML',
    'source_order'=>66, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'mpez','source_order'=>66,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'mppsc', 'name'=>'MPPSC Recruitment Advertisements', 'organization'=>'Madhya Pradesh Public Service Commission',
    'government_level'=>'State', 'state'=>'Madhya Pradesh', 'department'=>null,
    'official_domain'=>'mppsc.mp.gov.in', 'recruitment_url'=>'https://www.mppsc.mp.gov.in/', 'crawler_mode'=>'HTML',
    'source_order'=>67, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'mppsc','source_order'=>67,'listing_is_recruitment'=>false,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'niot', 'name'=>'NIOT Recruitments', 'organization'=>'National Institute of Ocean Technology',
    'government_level'=>'Central', 'state'=>'Tamil Nadu', 'department'=>null,
    'official_domain'=>'niot.res.in', 'recruitment_url'=>'https://www.niot.res.in/recruitment_details.php', 'crawler_mode'=>'HTML',
    'source_order'=>68, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'niot','source_order'=>68,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'nit-rourkela', 'name'=>'NIT Rourkela Recruitment', 'organization'=>'National Institute of Technology Rourkela',
    'government_level'=>'Central', 'state'=>'Odisha', 'department'=>null,
    'official_domain'=>'nitrkl.ac.in', 'recruitment_url'=>'https://www.nitrkl.ac.in/Career/', 'crawler_mode'=>'HTML',
    'source_order'=>69, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'nit-rourkela','source_order'=>69,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'nit-silchar', 'name'=>'NIT Silchar Recruitments', 'organization'=>'National Institute of Technology Silchar',
    'government_level'=>'Central', 'state'=>'Assam', 'department'=>null,
    'official_domain'=>'nits.ac.in', 'recruitment_url'=>'https://www.nits.ac.in/recruitment-view-all', 'crawler_mode'=>'HTML',
    'source_order'=>70, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'nit-silchar','source_order'=>70,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'npcil', 'name'=>'NPCIL Careers', 'organization'=>'Nuclear Power Corporation of India Limited',
    'government_level'=>'Central', 'state'=>null, 'department'=>null,
    'official_domain'=>'npcilcareers.co.in', 'recruitment_url'=>'https://www.npcilcareers.co.in/', 'crawler_mode'=>'AUTO',
    'source_order'=>71, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'npcil','source_order'=>71,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'prl', 'name'=>'PRL Advertisements', 'organization'=>'Physical Research Laboratory',
    'government_level'=>'Central', 'state'=>'Gujarat', 'department'=>null,
    'official_domain'=>'prl.res.in', 'recruitment_url'=>'https://www.prl.res.in/prl-eng/advertisement', 'crawler_mode'=>'HTML',
    'source_order'=>72, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'prl','source_order'=>72,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'rrc-eastern-railway', 'name'=>'RRC Eastern Railway Notice Board', 'organization'=>'Railway Recruitment Cell Eastern Railway',
    'government_level'=>'Central', 'state'=>'West Bengal', 'department'=>null,
    'official_domain'=>'rrcer.org', 'recruitment_url'=>'https://www.rrcer.org/notice_board.html', 'crawler_mode'=>'HTML',
    'source_order'=>73, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'rrc-eastern-railway','source_order'=>73,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'raman-research', 'name'=>'Raman Research Institute Openings', 'organization'=>'Raman Research Institute',
    'government_level'=>'Central', 'state'=>'Karnataka', 'department'=>null,
    'official_domain'=>'rri.res.in', 'recruitment_url'=>'https://www.rri.res.in/careers/regular-other-openings', 'crawler_mode'=>'HTML',
    'source_order'=>74, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'raman-research','source_order'=>74,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'svnit', 'name'=>'SVNIT Jobs', 'organization'=>'Sardar Vallabhbhai National Institute of Technology Surat',
    'government_level'=>'Central', 'state'=>'Gujarat', 'department'=>null,
    'official_domain'=>'svnit.ac.in', 'recruitment_url'=>'https://www.svnit.ac.in/web/jobs.php', 'crawler_mode'=>'HTML',
    'source_order'=>75, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'svnit','source_order'=>75,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'tgpsc', 'name'=>'Telangana PSC Applications and Notifications', 'organization'=>'Telangana Public Service Commission',
    'government_level'=>'State', 'state'=>'Telangana', 'department'=>null,
    'official_domain'=>'tgpsc.gov.in', 'recruitment_url'=>'https://www.tgpsc.gov.in/', 'crawler_mode'=>'HTML',
    'source_order'=>76, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'tgpsc','source_order'=>76,'listing_is_recruitment'=>false,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
  [
    'source_key'=>'udupi-csl', 'name'=>'Udupi Cochin Shipyard Careers', 'organization'=>'Udupi Cochin Shipyard Limited',
    'government_level'=>'Central', 'state'=>'Karnataka', 'department'=>null,
    'official_domain'=>'udupicsl.com', 'recruitment_url'=>'https://www.udupicsl.com/index.php/careers/', 'crawler_mode'=>'HTML',
    'source_order'=>77, 'check_frequency_minutes'=>360,
    'settings'=>['source_key'=>'udupi-csl','source_order'=>77,'listing_is_recruitment'=>true,'force_browser'=>false,'max_items'=>80,'verified'=>true],
  ],
];
